# composite action
# https://docs.github.com/en/actions/creating-actions
name: 'Get & Cache Dependencies'
description: 'Get npm depencies and chache them.'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: | 
        cd react
        npm ci
      shell: bash