# composite action
# https://docs.github.com/en/actions/creating-actions
name: 'Get & Cache Dependencies'
description: 'Get npm depencies and chache them.'
inputs:
  caching:
    description: 'Disable/Enable caching'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether cache was used'
    value: ${{ steps.install.caching }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: intall
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: | 
        cd react
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash