name: Deploy React Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd react
          npm ci
      - name: Run Tests
        run: |
          cd react 
          npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd react
          npm ci
      - name: Build Project
        run: |
          cd react
          npm run build
      - name: Deploy
        run: echo "Deploying ..."
      
    